// import localFont from 'next/font/local'
import "./globals.css"
import Navbar from './components/Navbar'

// const pretendard = localFont({
//   src: '../public/fonts/PretendardVariable.woff2',
//   display: 'swap',
// })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={pretendard.className}> */}
      <body>
        <div id="wrap">
          <Navbar />
          <div id="content">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
